name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_NAME: simple-java-app
          COMMIT_HASH: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:$COMMIT_HASH -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$COMMIT_HASH
          docker push $IMAGE_NAME:latest
