name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker image
        run: docker build -t simple-java-app:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag simple-java-app:${{ github.sha }} simple-java-app:latest
          docker tag simple-java-app:${{ github.sha }} simple-java-app:${{ github.sha }}

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.bianca15 }} -p ${{ secrets.bianca15 }}

      - name: Push Docker image
        run: |
          docker push simple-java-app:latest
          docker push simple-java-app:${{ github.sha }}
